### ISSUE TITLE
TypeError: get_checkpoint_state() missing 1 required positional argument: 'checkpoint_dir'

### ISSUE THREAD

**Issue by MayMiao0923** [jtkim-kaist/Speech-enhancement#15]
when i  run the train.py, i got the following error.

Traceback (most recent call last):
  File "E:\pycharm\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1689, in <module>
    main()
  File "E:\pycharm\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1683, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "E:\pycharm\PyCharm 2018.3\helpers\pydev\pydevd.py", line 1083, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\pycharm\PyCharm 2018.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/Speech-enhancement/SpeechEnhancement/Speech-enhancement/SE/lib/train.py", line 378, in <module>
    main()
  File "F:/Speech-enhancement/SpeechEnhancement/Speech-enhancement/SE/lib/train.py", line 304, in main
    ckpt = tf.train.get_checkpoint_state()
TypeError: get_checkpoint_state() missing 1 required positional argument: 'checkpoint_dir'

And I saw a similar question on this website https://stackoverflow.com/questions/19034714/pygame-typeerror-missing-1-required-positional-argument . Is the method mentioned in it used to solve my problem is feasible?

**Comment by MayMiao0923** [comment]
@jtkim-kaist

**Comment by ucasiggcas** [comment]
分开跑的？不是main.py ？

**Comment by MayMiao0923** [comment]
我用了train.py和main.py 都跑了都出现了上面这个问题，然后我现在在train.py 中233行的
    ckpt = tf.train.get_checkpoint_state()
中进行了修改
    ckpt = tf.train.get_checkpoint_state('./model/')
现在出现的是MemoryError 我不知道我这个做法是不是正确的 我在网上看到有人是这么做的
@ucasiggcas

**Comment by ucasiggcas** [comment]
你训练完了？？你的loss如何？

**Comment by MayMiao0923** [comment]
我正在调Python代码 我在运行程序的 时候 报了下面的错误  
如果我将feat定义为全局变量  那么  出现的是 feat is not defind
 
---Original---
