### ISSUE TITLE
TypeError: Cannot handle this data type

### ISSUE THREAD

**Issue by hlkang2380** [jtkim-kaist/Speech-enhancement#7]
hello, 
I have a problem and want to ask a question.
I started main.py without modifying the code, but I got an error.
I need advice on where to fix it.

Thank you

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2428, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 129), '|u1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khl/Desktop/prj_dir/SE/main.py", line 89, in <module>
    tr.main([prj_dir, logs_dir])
  File "./lib/train.py", line 353, in main
    train_summary.do_summary(m_valid, sess, eng, writer, itr)
  File "./lib/train.py", line 161, in do_summary
    writer.add_image(name + '_spectrogram_ref' + '/clean', clean_S, itr)  # image_shape = (C, H, W)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/writer.py", line 427, in add_image
    image(tag, img_tensor, dataformats=dataformats), global_step, walltime)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 216, in image
    image = make_image(tensor, rescale=rescale)
  File "/usr/local/lib/python3.6/dist-packages/tensorboardX/summary.py", line 254, in make_image
    image = Image.fromarray(tensor)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2431, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type

**Comment by HAEKADI** [comment]
Hello,
I had the same issue and I used **np.transpose()** to solve it. You're going to need to use it for all mentions of **writer.add_image()**.

`writer.add_image(name + '_spectrogram_ref' + '/clean', np.transpose(clean_S), itr) 
  writer.add_image(name + '_spectrogram_ref' + '/noisy', np.transpose(noisy_S), itr)`.

I Hope this helps!

**Comment by jtkim-kaist** [comment]
Thank you for your reply. I figure out that that error is from version difference of TensorboardX. I'll fix that part, soon.

**Comment by ucasiggcas** [comment]
Dear,

How to set the validation set ?
Please help me.
Thx

**Comment by ucasiggcas** [comment]
and 
`writer.add_image(name + '_spectrogram_enhanced' + '/enhanced', enhanced_S, itr)  # image_shape = (C, H, W)` in the same py file
also need `np.transpose` ?

I will try both.

**Comment by ucasiggcas** [comment]
1.
just modify the two
`writer.add_image(name + '_spectrogram_ref' + '/clean', np.transpose(clean_S), itr)  # image_shape = (C, H, W)`
`writer.add_image(name + '_spectrogram_ref' + '/noisy', np.transpose(noisy_S), itr)  # image_shape = (C, H, W)`
also has the same question

2.
I will try the second
modify all the three `writer.add_image`
`writer.add_image(name + '_spectrogram_enhanced' + '/enhanced', np.transpose(enhanced_S), itr)  # image_shape = (C, H, W)`
